name:                AOC2025
version:             0.1.0.0
github:              "githubuser/AOC2025"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

default-extensions: GHC2021

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AOC2025#readme>

dependencies:
- array
- base >= 4.7 && < 5
- bimap
#- comonad
- containers
#- distributive
- hashable
#- MemoTrie
- parsers
#- pqueue
#- recursion-schemes
#- regex-applicative
#- scientific
- split
- timeit
#- trie-simple
- unordered-containers
#- vector
- extra
- hmatrix
- MemoTrie
#- linearEqSolver
- sbv
- deepseq

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  AOC2025-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2025

tests:
  AOC2025-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2025
