resolver: lts-23.27 #nightly-2025-11-30

packages:
- .
#- ../../../Useful

extra-deps:
- linearEqSolver-2.4
#- regex-applicative-0.3.4
#- filtrable-0.1.6.0
#- cryptonite-0.30
#- tls-2.1.8

system-ghc: true
install-ghc: false
allow-newer: true


